name: liveshop_saas
description: SaaS de gestão para franquias de estúdios de liveshop

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
